### ISSUE TITLE
Multiple Connection - Postgresql

### ISSUE THREAD

**Issue by raultaufan** [totaljs/emptyproject-postgresql#1]
Dear @petersirka,
 
How about connection to multiple postgresql databases?

**Comment by petersirka** [comment]
Hi @raultaufan,
follow the code below:

- https://docs.totaljs.com/dbms/#usage

```js
require('dbms').init('postgresql://user:password@localhost:5432/database', ERROR('PostgreSQL'));
require('dbms').init('textdb', ERROR('TextDB'));
require('dbms').init('inmemory', 'inmemory', ERROR('InMemory'))
require('dbms').init('opendb://yourdomain.com?token=YOUR_TOKEN&ssl=1', ERROR('OpenDB'));

DBMS().insert('tbl_user', { id: UID(), name: 'Peter' }); // PostgreSQL
DBMS().insert('textdb/users', { id: UID(), name: 'Peter' }); // TextDB
DBMS().insert('inmemory/users', { id: UID(), name: 'Peter' }); // InMemory
```

**Comment by raultaufan** [comment]
multiple postgresql ,,

i try :
require('dbms').init('postgresql://user:password@localhost:5432/database1', ERROR('PostgreSQL'));
require('dbms').init('postgresql://user:password@localhost:5432/database2', ERROR('PostgreSQL'));
 
but found error on my query in database1

**Comment by petersirka** [comment]
```js
require('dbms').init('database1', 'postgresql://user:password@localhost:5432/database1', ERROR('PostgreSQL'));
require('dbms').init('database2', 'postgresql://user:password@localhost:5432/database2', ERROR('PostgreSQL'));
```

__Usage__:

```js
DBMS().find('database1/tbl_user').callback(console.log);
DBMS().find('database2/tbl_user').callback(console.log);
```

**Comment by raultaufan** [comment]
it's works.
but when I call the function or stored procedure which contains the **forward slash (/)** parameter, then an error appears.
_error: unterminated quoted string at or near "'{keywords:NUM"_

`var parameter = {keywords: "NUM/001"};
DBMS().find('database1/"function_open_order" (\'' + JSON.stringify(parameter ) + '\')').callback(function(err, response) {
});`

fyi, all queries are in stored procedure postgresql.

**Comment by raultaufan** [comment]
**### DONE**

Fixing on /node_modules/dbms/index.js line 935-936 

var tmp = table.split('/');
**var after = table.slice(table.indexOf('/') + 1);**
cache = { db: tmp.length > 1 ? tmp[0] : 'default', table: tmp.length > 1 ? **after** : tmp[0] };`

**Comment by petersirka** [comment]
Hi @raultaufan,
I'll look into it tomorrow. Thank you!

**Comment by molda** [comment]
@raultaufan have you tried using [query](https://docs.totaljs.com/dbms/40cff002bb50c/#4e38d001lw51c) method instead

```
DBMS().query('database1', '"function_open_order" (\' {"keywords": "NUM/001"} \')').callback(function(err, response) { });
```
It would seem more appropriate to me, especially because the documentation doesn't mention that you can do what you're doing with `find` method.

```
// db.find(name);
// @name {String} A collection/table name
// returns QueryBuilder
// response: Array

db.find('users');
```

**Comment by raultaufan** [comment]
it's work.
DONE.

Thanks @molda 
Thanks @petersirka 

My code for Stored Procedure / Function with Postgresql:
`DBMS().query('database1', 'SELECT "function_open_order" (\' {"keywords": "NUM/001"} \')').callback(function(err, response) { });`
